[build]
  command = "npm run netlify && ls -la .output/ && ls -la .output/public/ || (mkdir -p .output/public && cp index.html .output/public/)"
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "18"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 